site_name: 'backstage-enabled-application'

nav:
  - Home: 'test.md'
  - test: 'test.md'
  - readme: '/../README.md'
  - readme: '/README.md'
  - readme: '../README.md'
  - readme: './README.md'
  - readme: './../README.md'
  - readme: 'README.md'




plugins:
  - techdocs-core